charts/rasa-x/Chart.yaml, charts/rasa-x/templates/_helpers.tpl, charts/rasa-x/templates/rasa-x-volumeclaim.yaml, charts/rasa-x/values.yaml
Proposed Changes:
- remove hardcoded storage class
- fix https://github.com/RasaHQ/rasa-x-helm/issues/14
- only include `storageClassName` key in `pvc` when it's actually set to avoid issues with `helm upgrade`. (basically applying the solution from https://github.com/helm/charts/issues/20389#issuecomment-583854511)
=> don't hardcode storyclass-name

charts/rasa-x/Chart.yaml, charts/rasa-x/values.yaml
- don't specify runAsUser since this leads to problems with Duckling (duckling can't access it's binary in the path)
=> don't specify runAsUser since this leads to problems with Duckling

charts/rasa-x/Chart.yaml, charts/rasa-x/values.yaml
When I try to modify `extraEnvs` using a bash script, I update this value using the following command:
```
--set rasax.extraEnvs[0].name="QUICK_INSTALL",rasax.extraEnvs[0].value=true
```
However, it doesn't pass the validation because it's not explicitly specified that `extraEnvs` is an array.
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].env[20].value): invalid type for io.k8s.api.core.v1.EnvVar.value: got "array", expected "string"
```
This PR fixes this issue.
=> Explicitly specify that `extraEnvs` is an array, not string

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/_postgresql.tpl, charts/rasa-x/values.yaml
- bump Rasa X version to 0.26.0
- bump Rasa version to 1.8.1
- make use of `rasax.databaseName` in case it's specified (wasn't used before)
=> Rasa X 0.26.0

.github/workflows/ci.yml, charts/rasa-x/Chart.yaml, charts/rasa-x/templates/_helpers.tpl, charts/rasa-x/templates/event-service-deployment.yaml, charts/rasa-x/templates/rasa-config-files-configmap.yaml, charts/rasa-x/values.yaml
- make the login database for Rasa optional (`rasa.useLoginDatabase` value)
- make it possible to add additional environment variables for the event service deployments (`eventService.extraEnvs` variable)
=> optional login database and eventService extraEnvs

.github/workflows/ci.yml, .github/workflows/release.yml, charts/rasa-x/Chart.yaml, charts/rasa-x/templates/app-deployment.yaml, charts/rasa-x/templates/duckling-deployment.yaml, charts/rasa-x/templates/event-service-deployment.yaml, charts/rasa-x/templates/nginx-deployment.yaml, charts/rasa-x/templates/rasa-deployments.yaml, charts/rasa-x/templates/rasa-x-deployment.yaml, charts/rasa-x/values.yaml, ct.yaml
Changes:
- Both, chart-releaser and `chart-testing-action` published updates for Helm v3. Hence, we can switch back to use the officially maintained actions.
=> switch back to offical actions

charts/rasa-x/templates/event-service-deployment.yaml, charts/rasa-x/templates/rasa-x-deployment.yaml
[This PR](https://github.com/RasaHQ/rasa-x/pull/2494) removes the environment variable `LOCAL_MODE` in Rasa X. The variable should therefore not be set in the helm charts anymore.
=> remove LOCAL_MODE env variable

README.md, charts/rasa-x/Chart.yaml, charts/rasa-x/values.yaml
**Proposed Changes**:
* update readme with new versions and remove instructions to use `Chart.appVersion` to increment Rasa X version
* update default versions for Rasa Open Source and Rasa X
=> update readme and default Rasa versions

README.md, charts/rasa-x/Chart.yaml, charts/rasa-x/values.yaml
- latest patch for Rasa Open Source 
- update to new Rasa X minor (0.29)
- use Duckling 1.6.3 which has a much smaller Docker image size
=> bump image versions

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/app-service.yaml, charts/rasa-x/templates/ingress.yaml, charts/rasa-x/templates/nginx-configmap.yaml, charts/rasa-x/templates/nginx-deployment.yaml, charts/rasa-x/templates/nginx-service.yaml, charts/rasa-x/values.yaml
Relates to #32 
- Add `.Values.nginx.enabled` which defaults to true
- Can be disabled if using your own ingress solution
- This could be a set of Ingress objects as per the issue
- Could be a service mesh object such as an istio `VirtualService`
- Also removes a workaround port in the custom-actions app as the comment suggests it is only for nginx healthchecks
=> Add nginx.enabled flag

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/rasa-x-deployment.yaml, charts/rasa-x/templates/rasa-x-service.yaml
Fixes #61 
- Sets `SELF_PORT` environment variable in rasax
- This shouldn't hurt for the default values as it keep 5002
- The rasax service now points at the targetPort by name
- I have bumped the chart version to `1.4.1` assuming that #60 will be merged first (I can change that if needed)
=> Set SELF_PORT on rasax for custom ports

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/rasa-x-ingress.yaml
Rewrite definition for the `/api/chat` endpoint should include end of the line sign (`$`) to make sure that we rewrite requests only for the `/api/chat` endpoint.
=> Make sure to redirect requests only for the /api/chat endpoint

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/app-deployment.yaml, charts/rasa-x/templates/duckling-deployment.yaml, charts/rasa-x/templates/event-service-deployment.yaml, charts/rasa-x/templates/nginx-deployment.yaml, charts/rasa-x/templates/rasa-deployments.yaml, charts/rasa-x/templates/rasa-x-deployment.yaml, charts/rasa-x/values.yaml
**Proposed Changes**:
- fix https://github.com/RasaHQ/rasa-x-helm/issues/76
- disable mounting service credentials for all Rasa pods by default
- mounting the service credentials is optional for the `app` container in case users want to do some crazy stuff with Kubernetes
=> don't mount service credentials by default

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/rasa-config-files-configmap.yaml
`queue` has been deprecated in favor of `queues`, so our deployment files need updating 😊
=> Deprecating queue in favor of queues

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/_helpers.tpl, charts/rasa-x/templates/rasa-deployments.yaml, charts/rasa-x/templates/rasa-x-deployment.yaml
In some cases, changes in values are not relevant for the rasa-x deployment, but because we count checksum for the rasa and rasa-x values it triggers an upgrade even if it is not needed.  
Instead of counting checksum for the values, we should count checksum of templates for secrets and configmaps.
Fixes #69
=> Use checksum of templates instead of values

.github/workflows/ci.yml, .gitignore, README.md, charts/rasa-x/Chart.yaml, charts/rasa-x/templates/app-deployment.yaml, charts/rasa-x/templates/rasa-config-files-configmap.yaml, charts/rasa-x/templates/rasa-deployments.yaml, charts/rasa-x/values.yaml
Add support for the Jaeger sidecar [annotation](https://www.jaegertracing.io/docs/1.20/operator/#auto-injecting-jaeger-agent-sidecars) used by the [Jaeger Kubernetes Operator](https://www.jaegertracing.io/docs/1.20/operator/) as described in #88
=> Jaeger sidecar & addl endpoints

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/event-service-deployment.yaml
**Proposed Changes**:
Only use default `args` if no custom `args` are defined. Otherwise this can lead to a duplicate yaml key error
=> avoid 'arg' being specified twice

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/rasa-open-source-ingress.yaml, charts/rasa-x/templates/rasa-x-ingress.yaml, charts/rasa-x/values.yaml
Increase timeout for the proxy send and proxy read to 3600 seconds for the nginx ingress configuration.
=> Increase proxy read timeout and proxy send timeout for nginx-ingress

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/_helpers.tpl, charts/rasa-x/templates/db-migration-service-deployment.yaml, charts/rasa-x/values.yaml
Disable telemetry for the DB migration service if the Enterprise version is used.
=> Disable telemetry for the DB migration service

README.md, charts/rasa-x/Chart.yaml, charts/rasa-x/templates/_helpers.tpl, charts/rasa-x/templates/rasa-config-files-configmap.yaml, charts/rasa-x/templates/rasa-deployments.yaml, charts/rasa-x/values.yaml
**Proposed Changes**:
- fix https://github.com/RasaHQ/rasa-x-helm/issues/86
- introduce a new `.rasa.version` value which is used to the version checks to ensure backward compatibility. This is only used to construct the image tag in case `.Values.rasa.tag` is empty. If `Values.rasa.tag` is empty, a template constructs an image name `{.Values.rasa.version}-full` by default.
=> support non semantic Rasa image tags

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/app-deployment.yaml, charts/rasa-x/templates/db-migration-service-deployment.yaml, charts/rasa-x/templates/duckling-deployment.yaml, charts/rasa-x/templates/event-service-deployment.yaml, charts/rasa-x/templates/rasa-deployments.yaml, charts/rasa-x/templates/rasa-services.yaml, charts/rasa-x/templates/rasa-x-deployment.yaml, charts/rasa-x/values.yaml
Starting pods on https will make them fail their liveness probes; make this configurable via values.
=> make scheme of live/readiness probes configurable

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/nginx-deployment.yaml, charts/rasa-x/templates/rasa-config-files-configmap.yaml, charts/rasa-x/templates/rasa-deployments.yaml, charts/rasa-x/templates/rasa-x-config-files-configmap.yaml, charts/rasa-x/templates/rasa-x-deployment.yaml, charts/rasa-x/values.yaml
- make scheme (http/s) configurable for rasa, rasa-x and duckling
-  include full service DNS name in host paths 
Problem trying to solve: Providing https urls for model server/config endpoint etc. 
Why we can't just set the env var in values.yml: the default certs are valid only for the service DNS name. The full service DNS name needs {{ .Release.Namespace }} to be resolved, which isn't accessible from values.yml.
=> make scheme configurable, include full service DNS name

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/rasa-services.yaml, charts/rasa-x/templates/rasa-x-config-files-configmap.yaml, charts/rasa-x/values.yaml
- make it possible to annotate services separately, as they need their own ssl certificates. 
- correct the rasa-worker URL so that the ssl cert for it is valid.
=> Separate annotations for rasa services and use correct url for rasa-worker

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/ingress.yaml, charts/rasa-x/templates/rasa-open-source-ingress.yaml, charts/rasa-x/templates/rasa-x-ingress.yaml
- Remove deprecated `.Capabilities.KubeVersion.Version`
- Fix ingress spec for nginx container
=> Fix ingress spec for nginx container

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/rasa-config-files-configmap.yaml, charts/rasa-x/templates/rasa-x-deployment.yaml, charts/rasa-x/values.yaml
As part of https://github.com/RasaHQ/rasa-x/pull/4401 we need to have a new "cache" section in the `endpoints.yml`.
- Add new section to the config map
- Pass `REDIS_PASSWORD` env variable to the rasa-x pods
=> Add "cache" section to the endpoints.yml

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/event-service-deployment.yaml
Make the  REDIS_PASSWORD  env var available to the event service deployment, since https://github.com/RasaHQ/rasa-x-helm/pull/144/files introduces a section that requires the password, and the event service cannot read the endpoints file without it..
=> redis password for event service

.github/workflows/update_rasa_x_version.yml
Previously, the step ` Check if duplicated branch exists 🔍` fails with `exit code 1`. This is caused by the line 
```
BRANCH_NAME=$(git branch | grep -m 1 "bump-rasa-x-version-to-${LATEST_RASA_X_MINOR}")
```
When there is no `bump-to-rasa-x-version-XXXX` branch found, `grep` will return `exit code 1`, instead of an emty string `""`.  Now it is fixed by adding `|| echo ""` in the end. 
The workflow runs [as expected without any error](https://github.com/RasaHQ/rasa-x-helm/actions/runs/610975341), and correctly created a [PR](https://github.com/RasaHQ/rasa-x-helm/pull/152) bumping Rasa X version to `0.37.0`.
=> fix_update_rasa_x_version_workflow

charts/rasa-x/Chart.yaml, charts/rasa-x/values.yaml
Just a quick clarification that we don't support redis clusters because we use `redis-py` which does not support clusters: https://github.com/andymccurdy/redis-py#cluster-mode
=> Clarify lack of support for redis clusters

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/nginx-deployment.yaml, charts/rasa-x/values.yaml
make nginx liveness/readiness probe commands configurable so that e.g. when running with SSL it can be changed to port 8443
=> make nginx liveness/readiness probe commands configurable

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/nginx-deployment.yaml
The chart version including https://github.com/RasaHQ/rasa-x-helm/pull/168 broke for us with the error 
```
Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.containers[0].livenessProbe): unknown field "exec:command" in io.k8s.api.core.v1.Probe, ValidationError(Deployment.spec.template.spec.containers[0].readinessProbe): unknown field "exec:command" in io.k8s.api.core.v1.Probe]
```
When not overwriting the nginx probes, the chart in version 4d1a1f19a19d5c20a30126deffe669a1c71ae9e8 renders as:
```yaml
image: "rasa/nginx:0.38.1"
imagePullPolicy: Always
ports:
- name: "http"
containerPort: 8080
protocol: "TCP"
livenessProbe:
exec:command: # …
```
=> Fix default nginx probes

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/rasa-deployments.yaml, charts/rasa-x/values.yaml
Move `nodeSelector` under `rasa.versions` so that e.g. worker can select a node with specific requirements that prod does not share or vice versa
=> make nodes selectable per rasa version

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/rasa-open-source-api-ingress.yaml, charts/rasa-x/templates/rasa-open-source-channels-ingress.yaml
fix https://github.com/RasaHQ/rasa-x-helm/issues/193
Split the `rasa-x-rasa-open-source` ingress into two (`rasa-x-rasa-open-source-api` and `rasa-x-rasa-open-source-channels`), allowing the `/core/(.*)` forwarding rule to make use of the [rewrite target annotation](https://github.com/RasaHQ/rasa-x-helm/blob/main/charts/rasa-x/templates/rasa-open-source-ingress.yaml#L16), and the `webhooks/` and `socket.io` annotations to automatically create their respective `proxy_pass`es without the annotation.
=> split rasa open source ingress to fix forwarding

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/_helpers.tpl, charts/rasa-x/templates/rasa-config-files-configmap.yaml, charts/rasa-x/templates/rasa-deployments.yaml, charts/rasa-x/values.yaml
- Add template to include list of multiple rabbit queues as is possible in a docker-compose deployment for adding e.g. a queue for ELK to consume from
=> Add option to specify more than one rabbit queue

.github/deployments/rasa-x-helmfile.yaml, charts/rasa-x/Chart.yaml, charts/rasa-x/values.yaml
Also requested here: https://github.com/RasaHQ/rasa-x-helm/issues/12
I think we should have either nginx or ingress enabled by default. Currently, both are enabled. So with this PR I wanted to set nginx to the default by changing ingress enabled to false.
Also, in the comment we still referred to the nginx image as `rasa/nginx`, so I removed the rasa piece since we're no longer pulling our custom image.
=> Set ingress to false by default

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/rasa-deployments.yaml, charts/rasa-x/values.yaml
Allow users to disable the default Duckling image and provide a `RASA_DUCKLING_HTTP_URL ` within the `extraEnvs` section of the `rasa` service.
=> Configure duckling url

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/rasa-deployments.yaml, charts/rasa-x/templates/rasa-x-deployment.yaml, charts/rasa-x/values.yaml
- Add the `disableTelemetry` parameter for Rasa OSS - currently, it's automatically disabled if Rasa Enterprise is used
=> Add the disableTelemetry parameter for Rasa OSS

.github/workflows/changelog.yml, .github/workflows/release.yml, .github/workflows/update_rasa_x_version.yml
**The problem**
PRs created by `GITHUB_TOKEN` do not trigger any workflow runs. 
Examples: 
- https://github.com/RasaHQ/rasa-x-helm/pull/213
- https://github.com/RasaHQ/rasa-x-helm/pull/214
> When you use the repository's `GITHUB_TOKEN` to perform tasks on behalf of the GitHub Actions app, events triggered by the GITHUB_TOKEN will not create a new workflow run. 
> Ref: https://docs.github.com/en/actions/reference/authentication-in-a-workflow
**Proposed changes**
Replace all `GITHUB_TOKEN` secret to Rasabot.
=> Use Rasabot token

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/network-policy.yaml
Add network policies for Kubernetes API (the rabbitmq_peer_discovery_k8s plugin) and redis
=> fix: Add network policies for Kubernetes API and redis

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/_helpers.tpl, charts/rasa-x/templates/rasa-x-config-files-configmap.yaml
- Set an empty map for the 'rasa' key if environments are not defined
=> fix: Set an empty map for the `rasa` key if environments are not defined

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/_helpers.tpl, charts/rasa-x/templates/event-service-deployment.yaml, charts/rasa-x/templates/rasa-deployments.yaml, charts/rasa-x/values.yaml
- Use the same image for the init-db container as for the main container
- Resolves #249
=> refactor: Use the same image for the init-db container as for the main container

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/rasa-open-source-api-ingress.yaml, charts/rasa-x/templates/rasa-open-source-channels-ingress.yaml
- Don't create an ingress resource for Rasa OSS if Rasa OSS deployment is disabled
=> fix: Don't create ingress for Rasa OSS if deployment is disabled

README.md, charts/rasa-x/Chart.lock, charts/rasa-x/Chart.yaml, charts/rasa-x/templates/_rabbitmq.tpl, charts/rasa-x/templates/network-policy.yaml, charts/rasa-x/templates/rasa-config-files-configmap.yaml, charts/rasa-x/values.schema.json, charts/rasa-x/values.yaml, examples/openshift-values.yaml
Resolves #258 
The rasa-x-helm chart in version 4.0.0 introduces the following breaking changes:
Update chart dependencies to the latest available version, below you can find listed a summary of major changes compared to the previous version used by the rasa-x-helm chart:
* Redis - the chart for Redis is updated to version 15.
- Credentials parameter are reorganized under the `auth` parameter.
- The `cluster.enabled` parameter is deprecated in favor of `architecture` parameter that accepts two values: `standalone` and `replication`.
- `securityContext.*` is deprecated in favor of `XXX.podSecurityContext` and `XXX.containerSecurityContext` (`XXX` can be replaces with `master` or `replica`).
- `redis.redisPort` is deprecated in favor of `master.service.port` and `replica.service.port`.
A …
=> breaking: Update dependencies

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/rasa-x-deployment.yaml, charts/rasa-x/templates/rasa-x-service.yaml, charts/rasa-x/values.yaml
-  Add support for overriding the `RASA_X_HOST` variable defined in the rasa-x deployment.
=> feat: Add support for overriding the `RASA_X_HOST` variable

charts/rasa-x/Chart.yaml, charts/rasa-x/values.yaml
-  Set the empty table as a default value for the rasax.hostAliases field
=> fix: Set the empty table as a default value for the rasax.hostAliases field

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/_postgresql.tpl, charts/rasa-x/templates/rasa-deployments.yaml
- Don't include DB envs if the `postgresql.install` is set to false
=> fix: Don't include DB envs if the `postgresql.install` is set to `false`

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/network-policy.yaml
This PR adds ensures that egress for allow-dns-access is restricted to the `kube-system` namespace.
=> feat: add namespaceSelector to egress rule for allow-dns-access

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/network-policy.yaml, charts/rasa-x/values.yaml
Some environments have OPA policies enforcing that there is a 'to' specified for any egress NetworkPolicy. 
This update adds new values (`networkPolicy.egress.apiCIDR` and `networkPolicy.egress.rasaxToHttpsCIDR` ) so that an address can be set.
=> feat: Add support for defining an IP block for egress network policies

charts/rasa-x/Chart.yaml, charts/rasa-x/values.yaml
Update the default empty value for nodeCIDR from {} to [] (table vs non-table warning when NetworkPolicies are enabled)
=> Update values.yaml for correct nodeCIDR default value

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/network-policy.yaml
The extra '-' was causing the egress-from-rasa-x-to-rasa-production not to get deployed due to a missing newline
=> remove a - from line 167 which caused a missing netpol

charts/rasa-x/Chart.yaml, charts/rasa-x/values.yaml
The default duckling image tag of 0.1.6.3 needs to be bumped to the latest (0.2.0.2)
=> bump tag version for duckling

charts/rasa-x/templates/NOTES.txt
Show environments in the output to help users with the initial setup.
```
You have to add a deployment and training environment manually.
- http://example.com/environments
- http://example.net/environments
Rasa production environment: http://ee-rasa-x-rasa-production.rasa-ee.svc:5005
Rasa worker environment: http://ee-rasa-x-rasa-worker.rasa-ee.svc:5005
```
[BT-175](https://rasahq.atlassian.net/browse/BT-175)
=> [BT-175] Show environments URLs after helm run

charts/rasa-x/Chart.lock, charts/rasa-x/Chart.yaml
- Reuploaded Bitnami charts to Rasa-hosted Helm repo
- Swap repos to the Rasa ones
I think this does increase the version of Helm required to 3.8+ to support OCI repos.
=> Fix Bitnami removing charts from their index

.github/workflows/release.yml
Update the version of Helm and the Helm release action to resolve release failures since we switched to use OCI repos.
=> Update Helm Release components

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/rasa-config-files-configmap.yaml, charts/rasa-x/values.yaml
This update is based on the latest patch for Rasa OSS for `enable_selective_domain` in the action_endpoint. This change meant that we need to update our configMap so we can fetch this boolean value from the Values.yml file..
It is defaulted to False which means all Rasa server <--> Action Server communication will include the domain file however with enable_selective_domain set to `true`, only actions that requires a domain file will receive the domain file instead of all of them. This massively improves the performance for the communication between the two services.
=> feat: add enable_selective_domain in action_endpoint

.gitignore, charts/rasa-x/Chart.yaml, charts/rasa-x/templates/rasa-config-files-configmap.yaml, charts/rasa-x/templates/rasa-open-source-api-ingress.yaml, charts/rasa-x/templates/rasa-open-source-channels-ingress.yaml, charts/rasa-x/templates/rasa-x-ingress.yaml, charts/rasa-x/values.yaml
Improvements:
Ability to provide a custom model server location
If the ingress is not nginx, provide the ability for removal of nginx-related annotations
Additional granularity for ingress annotations on the api and channels ingress objects
=> Model server param

charts/rasa-x/Chart.yaml, charts/rasa-x/nginx-config-files/nginx.conf, charts/rasa-x/values.yaml
**Scenario**
Deployment with
```yaml
nginx:
enabled: true
```
and read only file systems enforced.
This may not be a classic or common scenario, as most of the time having only ingresses is enough, but it may still be possible and given that the chart supports it I think it's worth opening this PR.
**Problem**
```
pid "/etc/nginx/nginx.pid";
```
and 
```
client_body_temp_path  "/etc/nginx/client_body" 1 2;
proxy_temp_path        "/etc/nginx/proxy" 1 2;
fastcgi_temp_path      "/etc/nginx/fastcgi" 1 2;
scgi_temp_path         "/etc/nginx/scgi" 1 2;
uwsgi_temp_path        "/etc/nginx/uwsgi" 1 2;
```
are all in the root of the nginx configuration folder.
While the temp path could be mounted one by one, making lots of noise in the chart configuration, the same workaround can't be applied to the …
=> feat(nginx): allow to specify run path for nginx.pid and tmp folders
