charts/rasa-x/Chart.yaml, charts/rasa-x/templates/_rabbitmq.tpl, charts/rasa-x/templates/_redis.tpl
remove duplicate spaces which made kots.io fail
=> remove duplicated spaces

README.md, charts/rasa-x/Chart.yaml, charts/rasa-x/values.yaml
=> Set a default securityContext

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/_helpers.tpl, charts/rasa-x/templates/_postgresql.tpl, charts/rasa-x/values.yaml
=> Storage class, DB env

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/rasa-config-files-configmap.yaml, charts/rasa-x/values.yaml
make it an object instead of a json string to ease passing in values
=> make additionalChannelCredentials an object

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/_helpers.tpl, charts/rasa-x/templates/duckling-service.yaml, charts/rasa-x/templates/rasa-deployments.yaml
let's try this again 😄
- close #36
=> add duckling url env var

README.md, charts/rasa-x/Chart.yaml, charts/rasa-x/templates/_helpers.tpl, charts/rasa-x/templates/app-deployment.yaml, charts/rasa-x/templates/duckling-deployment.yaml, charts/rasa-x/templates/event-service-deployment.yaml, charts/rasa-x/templates/nginx-deployment.yaml, charts/rasa-x/templates/rasa-deployments.yaml, charts/rasa-x/templates/rasa-x-deployment.yaml, charts/rasa-x/values.yaml
- Resolve #55
- Bump appVersion to 0.30.1
=> Support full startup command replacement (#55)

README.md, charts/rasa-x/Chart.yaml, charts/rasa-x/templates/app-deployment.yaml, charts/rasa-x/templates/duckling-deployment.yaml, charts/rasa-x/templates/event-service-deployment.yaml, charts/rasa-x/templates/nginx-deployment.yaml, charts/rasa-x/templates/rasa-deployments.yaml, charts/rasa-x/templates/rasa-x-deployment.yaml, charts/rasa-x/values.yaml
- Add the `progressDeadlineSeconds` field for deployments
=> Add progressDeadlineSeconds

.github/workflows/ci.yml, charts/rasa-x/Chart.lock, charts/rasa-x/Chart.yaml, charts/rasa-x/values.yaml
Bump up the rabbitmq chart to 6.19.2
=> Bump the rabbitmq helm chart to 6.19.2

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/rasa-ingress.yaml, charts/rasa-x/templates/rasa-open-source-ingress.yaml, charts/rasa-x/templates/rasa-x-ingress.yaml, charts/rasa-x/values.yaml
Add support for Nginx ingress. #32
=> Use nginx ingress

charts/rasa-x/Chart.yaml, charts/rasa-x/values.schema.json
=> Validate RabbitMQ password

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/app-deployment.yaml, charts/rasa-x/templates/event-service-deployment.yaml, charts/rasa-x/templates/nginx-deployment.yaml, charts/rasa-x/templates/rasa-deployments.yaml, charts/rasa-x/templates/rasa-x-deployment.yaml, charts/rasa-x/values.yaml
=> Add support for extra volumes

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/_helpers.tpl, charts/rasa-x/templates/event-service-deployment.yaml, charts/rasa-x/templates/rasa-deployments.yaml, charts/rasa-x/templates/rasa-x-deployment.yaml
Disable telemetry for ee version.
=> Disable telemetry

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/rasa-config-files-configmap.yaml
Add exceptions for not Semantic Versions, e.g. `2.0.0a1`
=> Add exceptions for not Semantic Versions

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/rasa-deployments.yaml
- Create a temporary directory for the Rasa global configuration
- Set `MPLCONFIGDIR` to `/tmp/.matplotlib`
Fixes #77
=> Mount tmp dir for the config directory

.github/workflows/ci.yml, charts/rasa-x/Chart.yaml, charts/rasa-x/templates/_helpers.tpl, charts/rasa-x/templates/db-migration-service-deployment.yaml, charts/rasa-x/templates/db-migration-service.yaml, charts/rasa-x/templates/event-service-deployment.yaml, charts/rasa-x/templates/rasa-deployments.yaml, charts/rasa-x/templates/rasa-x-deployment.yaml, charts/rasa-x/values.yaml
=> Add the database migration service

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/_helpers.tpl
Fix incorrect address for the DB migration service.
=> Fix the DB migration service address

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/db-migration-service-deployment.yaml, charts/rasa-x/templates/duckling-deployment.yaml, charts/rasa-x/templates/event-service-deployment.yaml, charts/rasa-x/templates/nginx-deployment.yaml, charts/rasa-x/templates/rasa-deployments.yaml, charts/rasa-x/templates/rasa-x-deployment.yaml, charts/rasa-x/values.yaml
Make the `automountServiceAccountToken` configurable.
=> Make the automountServiceAccountToken parameter configurable

.github/workflows/ci.yml, charts/rasa-x/Chart.yaml, charts/rasa-x/templates/rasa-x-ingress.yaml
Closes https://github.com/RasaHQ/rasa-x/issues/3807
=> Disallow indexing - nginx-ingress

.github/workflows/ci.yml, charts/rasa-x/Chart.yaml, charts/rasa-x/templates/db-migration-service-deployment.yaml, tests/db_migration_service_test.go
- Add unit tests
- Fix an issue with the `if` condition for the db-migration service args
=> Fix args for the db migration service 

.github/workflows/release.yml
=> ci: Fix the release workflow

.github/CODEOWNERS, .github/workflows/ci.yml, .github/workflows/update_rasa_x_version.yml
When there is a new PR, automatically send a request for review to [CODEOWNERS](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners). 
- The infrastructure team is responsible for the entire repo
=> Assign reviewer to pr

charts/rasa-x/Chart.yaml, charts/rasa-x/values.yaml
- Pin the alpine image version to 3.12.3
=> Use alpine 3.12.3 for the init-db container

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/ingress.yaml, charts/rasa-x/templates/rasa-open-source-ingress.yaml, charts/rasa-x/templates/rasa-x-ingress.yaml
=> fix: updating apiVersion for ingress

charts/rasa-x/Chart.yaml, charts/rasa-x/values.yaml
=> other: Update Rasa to 2.2.7

.github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/update_rasa_x_version.yml
- follow-up of https://github.com/RasaHQ/rasa/issues/6028
- rename old `master` occurrences to `main`
=> prepare rename to 'main'

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/app-deployment.yaml, charts/rasa-x/templates/db-migration-service-deployment.yaml, charts/rasa-x/templates/duckling-deployment.yaml, charts/rasa-x/templates/event-service-deployment.yaml, charts/rasa-x/templates/nginx-deployment.yaml, charts/rasa-x/templates/rasa-deployments.yaml, charts/rasa-x/templates/rasa-x-deployment.yaml, charts/rasa-x/values.yaml, tests/app_test.go, tests/db_migration_service_test.go, tests/duckling_test.go, tests/event_service_test.go, tests/main_test.go, tests/nginx_test.go, tests/rasa_test.go, tests/rasa_x_test.go
Add the `podLabels` parameter in order to add extra labels to pods
=> Add additional labels to pods

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/event-service-deployment.yaml, charts/rasa-x/templates/nginx-service.yaml, charts/rasa-x/values.yaml
Add the option to specify loadBalancerSourceRanges in values for AWS deployments
=> add loadBalancerSourceRanges to nginx service

.github/deployments/rasa-x-helmfile.yaml, charts/rasa-x/Chart.yaml, charts/rasa-x/templates/nginx-conf-configmap.yaml
- Fix ConfigMap template for Nginx
=> fix: Fix configmap template for nginx

charts/rasa-x/values.yaml
=> Corrected comments of livenessProbe and readinessProbe for consistency

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/_helpers.tpl, charts/rasa-x/templates/duckling-deployment.yaml, charts/rasa-x/values.yaml
Add extra env vars option for Duckling
=> Allow extra env vars for Duckling

README.md
README was lagging behind with what is stated in `values.yaml`.
=> Update tags in README

charts/rasa-x/Chart.yaml, charts/rasa-x/values.yaml
Revert https://github.com/RasaHQ/rasa-x-helm/pull/208
=> Set ingress.enable to true by default

README.md
=> typo: fix link to LICENSE

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/network-policy.yaml
- Move the egress-from-rasa-x-to-https network policy out of if condition
=> fix: Move the egress-from-rasa-x-to-https network policy out of if condition

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/_helpers.tpl, charts/rasa-x/templates/rasa-x-deployment.yaml, charts/rasa-x/values.yaml
- Add an option to define hostNetwork and DNS policy for the rasa-x deployment
=> Add an option to define hostNetwork and DNS policy for the rasa-x 

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/rasa-x-config-files-configmap.yaml
Include the 'rasa' key in the environment's configuration
=> Include the 'rasa' key in the environment's configuration

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/rasa-config-files-configmap.yaml, charts/rasa-x/values.yaml
Resolves #238 
- Add support for the `query` field to configmap for rasa tracker store configuration
=> Add support for the query field to configmap 

.github/deployments/ingress-nginx-helmfile.yaml, charts/rasa-x/Chart.yaml, charts/rasa-x/templates/network-policy.yaml
- Add a network policy for rabbitmq clustering
=> feat: Add a network policy for rabbitmq clustering

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/_helpers.tpl, charts/rasa-x/values.yaml
- Add support for defining resources for the init-db container.
=> feat: Add support for defining resources for the init-db container

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/rasa-x-ingress.yaml
Fix #246 and tackles CVE-2021-25742
https://github.com/RasaHQ/rasa-x/pull/7186
=> Remove robots.txt from annotation

charts/rasa-x/Chart.yaml, charts/rasa-x/values.yaml
- Change incorrect field name from `rasa.versions.rasaXXX.external.host` to `rasa.versions.rasaXXX.external.url` in the values file
=> fix: Change incorrect field name from `rasa.versions.rasaXXX.external.host` to `rasa.versions.rasaXXX.external.url` in the values file

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/rasa-x-deployment.yaml, charts/rasa-x/values.yaml
- Add support for setting `hostAliases` for the rasa-x deployment.
=> feat: Add support for setting `hostAliases` for the rasa-x deployment

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/rasa-x-ingress.yaml
=> fix: add ingressClassName field to rasa-x ingress

README.md
Update helm chart README to the correct rasa.com/docs link
=> Update link to rasa docs

charts/rasa-x/templates/event-service-deployment.yaml, charts/rasa-x/templates/rasa-config-files-configmap.yaml, charts/rasa-x/templates/rasa-deployments.yaml, charts/rasa-x/templates/rasa-x-deployment.yaml, charts/rasa-x/values.yaml
added support for external redis host and redis pw via k8s secret
https://github.com/RasaHQ/rasa-x-helm/issues/247
=> Redis external pw

charts/rasa-x/Chart.yaml
bump version to 4.4.1 with comment to release helm chart
=> helmchart version bump

charts/rasa-x/templates/_helpers.tpl, charts/rasa-x/templates/event-service-deployment.yaml, charts/rasa-x/templates/rasa-deployments.yaml, charts/rasa-x/templates/rasa-x-deployment.yaml
=> Enable telemetry by default

.gitignore, charts/rasa-x/templates/rasa-config-files-configmap.yaml, charts/rasa-x/values.yaml
- Fixes [ATO-310](https://rasahq.atlassian.net/browse/ATO-310) ... or at least tries to 😅
=> ATO-313 Add configuration for rasa-plus lock-store in rasa configmap template

charts/rasa-x/Chart.yaml
- Bump chart version
- Bump Rasa EE to 1.2.2
- Add changelog for release
=> Increase chart version

charts/rasa-x/Chart.yaml, charts/rasa-x/templates/app-deployment.yaml, charts/rasa-x/templates/db-migration-service-deployment.yaml, charts/rasa-x/templates/event-service-deployment.yaml, charts/rasa-x/templates/rasa-deployments.yaml, charts/rasa-x/templates/rasa-x-deployment.yaml, charts/rasa-x/values.yaml
- Add pod annotations for Rasa X pods
=> Add podAnnotations to Rasa X deployments

charts/rasa-x/templates/_helpers.tpl, charts/rasa-x/values.yaml
- Follow the Bitnami pattern and provide an enabled flag for all occurrences of securityContext
- Security context will be enabled on all containers with current setup
=> [INFRA-319] Enable security context
